### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by faculb** [TowelSniffer/Anki-go#1]
Hi, sorry to bother you.

I don't have any problem with the note, it's more like a wish.

I'd like to have some random rotation of the positions on the board. I don't like to see the same problems in the same way all the time.

Do you have some syntax for that?

Thank you.

**Comment by TowelSniffer** [comment]
This may be easy to achieve with some CSS/JavaScript. Perhaps just the transform property set to a random orientation. If you want the rotation to be the same on the backside you could use anki persistence. I will have a quick look after work, might be a good feature.

**Comment by TowelSniffer** [comment]
ok so this can sort of be done by adding something like the following towards the end of the template under where it calls `besogo.autoInit()`

```
var orientation = ["0deg","90deg","180deg","270deg"]
boardOrientation = orientation[Math.floor(Math.random() * orientation.length)];
document.getElementsByClassName("besogo-board")[0].style.transform = "rotate("+boardOrientation+")";
```

getting the backside to rotate unfortunately won't work well as the letters showing the variations will be upside down. unfortunately besgo, the viewer these cards use, doesn't include a rotate board feature. 

ima close this issue as it doesn't work as cleanly as i'd hoped

**Comment by trdischat** [comment]
I posted a solution to this in #5.
