### ISSUE TITLE
Bulk sgf import

### ISSUE THREAD

**Issue by bixbyr** [TowelSniffer/Anki-go#4]
I am using Anki on MacOS along with Anki-go. As far as I can tell there is no way to import more than one sgf at a time? The import menu does not accept sgf files. I am trying to load a significant tsumego collection into Anki, copy and pasting one sgf file text at a time into a box is not a workable solution.

Is there supposed to be a way to import more than one sgf file at a time or is that unsupported at this time?

**Comment by TowelSniffer** [comment]
This is very doable, but it does help if you have experience with both writing scripts and regex. I have actually done exactly what you are trying to do before. I don't remember exactly what I did but basically you need to combine all the sgf files into one text file (I wrote a script for this but there may be a tool.that can do this), then use a text editor that supports regex to bulk edit the file so that each sgf occupies one line of that text file. Then simply import that file. It will take you a lot of googling but it's easier than you might think.

**Comment by bixbyr** [comment]
If one sgf per line of the file is supported I can easily do that. Then just create a card, paste, and it will get separated out?Sent from my iPadOn Apr 22, 2023, at 9:48 PM, TowelSniffer ***@***.***> wrote:﻿
This is very doable, but it does help if you have experience with both writing scripts and regex. I have actually done exactly what you are trying to do before. I don't remember exactly what I did but basically you need to combine all the sgf files into one text file, then use a text editor that supports regex to bulk edit the file so that each sgf occupies one line of that text file. Then simply import that file. It will take you a lot of googling but it's easier than you might think.

**Comment by TowelSniffer** [comment]
Yeah so basically when you import a text file into anki, it looks for fields seperated by like a comma or a tab, and any new line it considers a new note. As the go template only has one field, you don't need to worry about field seperation. Having each sgf on a single line is all you need.

**Comment by bixbyr** [comment]
When I tried creating a new card and in the sgf field put one sgf file on one line, and a second sgf file on the second line only  one card was created containing the first problem. I don't know if you meant that I was supposed to import the sgf file instead, however Anki does not allow sgf extensions when using the "Import file" option. For reference this was the file I attempted to bring in with two problems:

(;MULTIGOGM[1]AB[pb][qk][rj][qi][pi][ph][qf][pf][pe][pd][qc]AW[ri][rh][qh][qg][rf][qe][qd]C[����һ��]AP[MultiGo:3.9.4]SZ[19]CA[gb2312];B[sc](;W[rd];B[sg];W[sd];B[sf];W[rc];B[rb];W[sb];B[se]C[����ͼ����Χ����Ʒ])(;W[sg];B[se];W[si];B[sf]C[�仯ͼ]))
(;MULTIGOGM[1]AB[ri][ph][qh][rg][rf][mc][pf][pe][pd][pc][qb][rb]AW[rc][qc][qe][qf][qg][pg][ng][oh][oi][pj][qj][rj]C[�ɹ�һˮ]AP[MultiGo:3.9.4]SZ[19]CA[gb2312];B[se];W[rd];B[re];W[qd];B[sc]C[����ͼ����Χ����Ʒ])

**Comment by TowelSniffer** [comment]
Yeah just rename it to .CSV should do the trick

**Comment by bixbyr** [comment]
Ok, I found that if I edit the txt export which has no media I can replace individual lines with new problems and re import it. All the txt file needs apparently is to start with
#separator:tab
#html:false

Thanks for the help!

**Comment by TowelSniffer** [comment]
Yeah interesting, I was wondering about that because I know I have imported plain text files. Another easy way to make an importable text file is to export an excel spreadsheet in CSV format. Anyway good to hear you figured it out
