### ISSUE TITLE
Redundant code in latest release

### ISSUE THREAD

**Issue by trdischat** [TowelSniffer/Anki-go#8]
Thanks for release 1.2.12.!

Not a critical point, but I noticed a bit of redundant code, and that inspired me to do a little streamlining.

First, there are two `if (Persistence.isAvailable()) {}` blocks at the beginning of the script. You can safely delete the second one that only deals with `randVar`, since it fully duplicates the code in the first one.

Second, the variable `errorCheck` is no longer used anywhere in the script and can be completely eliminated. Now that you have added the variable `solvedColour`, I have changed every instance of `Persistence.setItem("errorCheck", <true|false>);` in the FRONT template to `Persistence.setItem("solvedColour", solvedColour);`. I then modified the BACK template to use this variable as follows:

```js
var solvedColour = "limegreen"; // If Persistence is enabled, this setting is ignored.

if (Persistence.isAvailable()) {
    solvedColour = Persistence.getItem("solvedColour");
    randVar = Persistence.getItem("rnd");
    if (randVar) {
        probVar = Persistence.getItem("var");
    }
    Persistence.clear();
}

document.getElementsByClassName("besogo-board")[0].style.border = "0.7vmin solid " + solvedColour;
document.getElementsByClassName("besogo-board")[0].style.boxShadow ="0px 0px 6px 0px " + solvedColour;
```
You can then fully eliminate `errorCheck` from the BACK templates as well.

**Comment by TowelSniffer** [comment]
Thanks mate I will add this on my next day off. Sorry for the mess lol. I don't have experience coding beyond making these anki templates but now that I know people are actually going through the code I will try to keep it organised.
