### ISSUE TITLE
how to use stone images in the media files folder?

### ISSUE THREAD

**Issue by Ka-lip** [TowelSniffer/Anki-go#9]
Hi,
Thanks for the amazing template. It totally fits my requirements.

I would like to know how to turn on the function to use images showing stones? I put the png files in my media folder but I couldn't find the corresponding variable to switch the function.

Thank you.

**Comment by TowelSniffer** [comment]
Busy at the moment but I will get around to answering this. Should have more free time next week

**Comment by TowelSniffer** [comment]
last update enables this. enable this variable in the note template. The delay in loading images can be annoying on slower devices fyi. 

var realstones = false;

**Comment by Ka-lip** [comment]
Sorry for the late reply. Thank you! The stones are beautiful now.

Thank you again for the awesome anki deck!

**Comment by Ka-lip** [comment]
One more comment.
In [README.me#first-move-of-puzzle](https://github.com/TowelSniffer/Anki-go?tab=readme-ov-file#first-move-of-puzzle), you set `var goFirst = false;` as default value.
But in my environment (Windows Anki and AnkiDroid), it works well with `var goFirst = true;`.
And the default value makes frame color incorrect.

Correct frame color: same as the player's color  (Black & Black)
![Image](https://github.com/user-attachments/assets/859eab16-bca7-4037-a58f-4a491fc00ca9)  

Wrong frame color: frame is black but the player's stone is white.
![Image](https://github.com/user-attachments/assets/9985da8e-99d4-4f94-aec8-3ab2d33c5424)
